name: Elliot Boney
description: Elliot Boney's Github site
author:
  name: Elliot Boney
  email: elliotboney@gmail.com

baseurl: //elliotboney.github.io

paginate: 5
paginate_path: '/blog/:num'


# Make local act like github
safe: true
permalink: /post/:title

timezone: America/Chicago

# Markdown Conversion
markdown: kramdown
kramdown:
  input: GFM

#collections
collections:
  tags:
    output: true

# Defaults
defaults:
-
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "default"
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    author: "Elliot Boney"
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - .bowerrc
    - .gitignore
    - bower.json
    - local.sh
    - manifest.json
    - README.md
    - .sass-cache